---
title: "Практическая работа №0"
author: "Arch"
format:
  md:
    output-file: README.md
  html: 
    output-file: README.html
---

# Подготовка воспроизводимых отчетов

## Цель работы

1.  Развернуть Rstudio;
2.  Развить практические навыки использования современного стека воспроизводимых исследований на языке R;

## ️Исходные данные

1.  R 4.4.1;
2.  RStudio 2024.04.2+764;

## Решение задачи

Для создания воспроизводимых отчётов используются два основных инструмента: *R Markdown* и *Quarto*. Оба используют синтаксис Markdown и интегрированы в R, но различаются функционалом.

### R Markdown

R Markdown — это облегчённый язык разметки с синтаксисом форматирования обычного текста. Основные возможности:

1.  Лёгкий доступный язык форматирования для не-программистов, позволяющий создавать интернет-страницы и другие документы;
2.  Возможность конвертировать код сразу во множество форматов;
3.  Поддерживаются следующие форматы экспорта: `HTML`, `Markdown`, `PDF`, `Word`;
4.  Возможность писать код не только на R, но и на других языках;
5.  Возможность создания полностью воспроизводимых документов, сочетающих код (расчёты, методы анализа) и текст.

### Quarto

Quarto — более современный и гибкий инструмент, который поддерживает не только R, но и другие языки программирования, такие как Python. Основные особенности:

1.  Quarto интегрирует поддержку для работы с проектами, что подволяет более эффективно управлять масштабными отчётами и документами;
2.  Quarto поддерживает расширяемость и пользовательские настройки, позволяя разработать собсвенные форматы и стили;
3.  С помощью Quarto можно создавать отчёты на разных языках в одном документе;
4.  Quarto основан на R Markdown, и многие функции R Markdown также доступны в Quarto;
5.  Render Quarto Markdown предоставляет также директорию с `{название}_files`, содержащую дополнительные конфигурационные файлы отчёта;

## ️Общий план выполнения

В ходе работы будет использоваться Quarto, ввиду более современного подхода и гибкости.

### Шаг 1: Настройка Quarto

Поскольку стабильная версия Quarto поставляется в комплекте с RStudio 2022.07.1+, установка в данном случае не требуется.

Удостоверимся, что Quarto присутствует и узнаем его версию:

```{teminal}
quarto check
```

### Шаг 2: Создание отчёта с использованием Quarto

#### 1. Создание нового документа:

-   Создайте новый файл Quarto: `File -> New File -> Quarto Document`;
-   Задайте заголовок, а также выберите тип выходных дынных (`HTML`, `Markdown`, `PDF`, `Word`) и движок (`None`, `Knitr`, `Jupyter`);

#### 2. Наполнение документа:

-   YAML-заголовок (начало документа), указав такие параметры как:

    -   `title` - название
    -   `author` - имя автора
    -   `format` - тип выходных данных

-   Желаемый текст в синтаксисе Markdown;

-   По желанию можно добавить динамический код:

```{R}
sum(trees)
```

#### 3. Просмотр результата:

-   В рабочей директории появился файл (`HTML`, `Markdown`, `PDF`, `Word`), который можно открыть, чтобы проверить корректность работы;

## ️Вывод

В результате проделанной работы, были основоены практические навыки использования современного стека воспроизводимых исследований на языке R, а также R Markdown и Quarto, которые являются мощными инструментами для создания воспроизводимых отчётов.